using Unity.Jobs;

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.PhysicsForceAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.PhysicsForceAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.PhysicsForceAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.PhysicsForceAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentDrainableTrackJob<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.ActiveForce, BovineLabs.Timeline.Physics.PhysicsForceState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.LatchDrainFinalizeJob<BovineLabs.Timeline.Physics.ActiveForce, BovineLabs.Timeline.Physics.PhysicsForceState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.ActiveForce, BovineLabs.Timeline.Physics.PhysicsForceMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsForceState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.AdvanceElapsedTimeJob<BovineLabs.Timeline.Physics.PhysicsForceData, BovineLabs.Timeline.Physics.PhysicsForceState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.PhysicsVelocityAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.PhysicsVelocityAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.PhysicsVelocityAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.PhysicsVelocityAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentDrainableTrackJob<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.ActiveVelocity, BovineLabs.Timeline.Physics.Data.PhysicsVelocityState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.LatchDrainFinalizeJob<BovineLabs.Timeline.Physics.Data.ActiveVelocity, BovineLabs.Timeline.Physics.Data.PhysicsVelocityState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.ActiveVelocity, BovineLabs.Timeline.Physics.Data.Mixers.PhysicsVelocityMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.Data.PhysicsVelocityState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.AdvanceElapsedTimeJob<BovineLabs.Timeline.Physics.Data.PhysicsVelocityData, BovineLabs.Timeline.Physics.Data.PhysicsVelocityState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Data.PhysicsDragData, BovineLabs.Timeline.Physics.Data.PhysicsDragAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Data.PhysicsDragData, BovineLabs.Timeline.Physics.Data.PhysicsDragAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Data.PhysicsDragData, BovineLabs.Timeline.Physics.Data.PhysicsDragAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.Data.PhysicsDragData, BovineLabs.Timeline.Physics.Data.PhysicsDragAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.Data.PhysicsDragData, BovineLabs.Timeline.Physics.Data.ActiveDrag>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.Data.PhysicsDragData, BovineLabs.Timeline.Physics.Data.ActiveDrag, BovineLabs.Timeline.Physics.Data.PhysicsDragMixer>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Chains.ChainFollowData, BovineLabs.Timeline.Physics.Chains.ChainFollowAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Chains.ChainFollowData, BovineLabs.Timeline.Physics.Chains.ChainFollowAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Chains.ChainFollowData, BovineLabs.Timeline.Physics.Chains.ChainFollowAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.Chains.ChainFollowData, BovineLabs.Timeline.Physics.Chains.ChainFollowAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.Chains.ChainFollowData, BovineLabs.Timeline.Physics.Chains.ActiveChainFollow>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.Chains.ChainFollowData, BovineLabs.Timeline.Physics.Chains.ActiveChainFollow, BovineLabs.Timeline.Physics.Chains.ChainFollowMixer>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData, BovineLabs.Timeline.Physics.PhysicsFilterOverrideAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData, BovineLabs.Timeline.Physics.PhysicsFilterOverrideAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData, BovineLabs.Timeline.Physics.PhysicsFilterOverrideAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData, BovineLabs.Timeline.Physics.PhysicsFilterOverrideAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData, BovineLabs.Timeline.Physics.ActiveFilterOverride>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData, BovineLabs.Timeline.Physics.ActiveFilterOverride, BovineLabs.Timeline.Physics.Data.Kernels.DiscreteMixer<BovineLabs.Timeline.Physics.PhysicsFilterOverrideData>>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateTrackJob<BovineLabs.Timeline.Physics.PhysicsFilterOverrideState, BovineLabs.Timeline.Physics.ActiveFilterOverride>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsGravityOverrideData, BovineLabs.Timeline.Physics.PhysicsGravityOverrideAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsGravityOverrideData, BovineLabs.Timeline.Physics.PhysicsGravityOverrideAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsGravityOverrideData, BovineLabs.Timeline.Physics.PhysicsGravityOverrideAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsGravityOverrideData, BovineLabs.Timeline.Physics.PhysicsGravityOverrideAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsGravityOverrideData, BovineLabs.Timeline.Physics.ActiveGravityOverride>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsGravityOverrideData, BovineLabs.Timeline.Physics.ActiveGravityOverride, BovineLabs.Timeline.Physics.PhysicsGravityOverrideMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateTrackJob<BovineLabs.Timeline.Physics.PhysicsGravityOverrideState, BovineLabs.Timeline.Physics.ActiveGravityOverride>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData, BovineLabs.Timeline.Physics.PhysicsKinematicOverrideAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData, BovineLabs.Timeline.Physics.PhysicsKinematicOverrideAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData, BovineLabs.Timeline.Physics.PhysicsKinematicOverrideAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData, BovineLabs.Timeline.Physics.PhysicsKinematicOverrideAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData, BovineLabs.Timeline.Physics.ActiveKinematicOverride>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData, BovineLabs.Timeline.Physics.ActiveKinematicOverride, BovineLabs.Timeline.Physics.Data.Kernels.DiscreteMixer<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideData>>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateTrackJob<BovineLabs.Timeline.Physics.PhysicsKinematicOverrideState, BovineLabs.Timeline.Physics.ActiveKinematicOverride>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsRicochetData, BovineLabs.Timeline.Physics.PhysicsRicochetAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsRicochetData, BovineLabs.Timeline.Physics.PhysicsRicochetAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsRicochetData, BovineLabs.Timeline.Physics.PhysicsRicochetAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsRicochetData, BovineLabs.Timeline.Physics.PhysicsRicochetAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsRicochetData, BovineLabs.Timeline.Physics.ActiveRicochet>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsRicochetData, BovineLabs.Timeline.Physics.ActiveRicochet, BovineLabs.Timeline.Physics.Data.Kernels.DiscreteMixer<BovineLabs.Timeline.Physics.PhysicsRicochetData>>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsRicochetState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsShapeResizeData, BovineLabs.Timeline.Physics.PhysicsShapeResizeAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsShapeResizeData, BovineLabs.Timeline.Physics.PhysicsShapeResizeAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsShapeResizeData, BovineLabs.Timeline.Physics.PhysicsShapeResizeAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsShapeResizeData, BovineLabs.Timeline.Physics.PhysicsShapeResizeAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsShapeResizeData, BovineLabs.Timeline.Physics.ActiveShapeResize>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsShapeResizeData, BovineLabs.Timeline.Physics.ActiveShapeResize, BovineLabs.Timeline.Physics.Data.Kernels.DiscreteMixer<BovineLabs.Timeline.Physics.PhysicsShapeResizeData>>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateTrackJob<BovineLabs.Timeline.Physics.PhysicsShapeResizeState, BovineLabs.Timeline.Physics.ActiveShapeResize>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsShapeSwapData, BovineLabs.Timeline.Physics.PhysicsShapeSwapAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsShapeSwapData, BovineLabs.Timeline.Physics.PhysicsShapeSwapAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsShapeSwapData, BovineLabs.Timeline.Physics.PhysicsShapeSwapAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsShapeSwapData, BovineLabs.Timeline.Physics.PhysicsShapeSwapAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsShapeSwapData, BovineLabs.Timeline.Physics.ActiveShapeSwap>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsShapeSwapData, BovineLabs.Timeline.Physics.ActiveShapeSwap, BovineLabs.Timeline.Physics.Data.Kernels.DiscreteMixer<BovineLabs.Timeline.Physics.PhysicsShapeSwapData>>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateTrackJob<BovineLabs.Timeline.Physics.PhysicsShapeSwapState, BovineLabs.Timeline.Physics.ActiveShapeSwap>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Sockets.SocketReturnData, BovineLabs.Timeline.Physics.Sockets.SocketReturnAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Sockets.SocketReturnData, BovineLabs.Timeline.Physics.Sockets.SocketReturnAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.Sockets.SocketReturnData, BovineLabs.Timeline.Physics.Sockets.SocketReturnAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.Sockets.SocketReturnData, BovineLabs.Timeline.Physics.Sockets.SocketReturnAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.Sockets.SocketReturnData, BovineLabs.Timeline.Physics.Sockets.ActiveSocketReturn>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.Sockets.SocketReturnData, BovineLabs.Timeline.Physics.Sockets.ActiveSocketReturn, BovineLabs.Timeline.Physics.Sockets.SocketReturnMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.Sockets.SocketReturnState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsSplineFollowData, BovineLabs.Timeline.Physics.PhysicsSplineFollowAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsSplineFollowData, BovineLabs.Timeline.Physics.PhysicsSplineFollowAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsSplineFollowData, BovineLabs.Timeline.Physics.PhysicsSplineFollowAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsSplineFollowData, BovineLabs.Timeline.Physics.PhysicsSplineFollowAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsSplineFollowData, BovineLabs.Timeline.Physics.ActiveSplineFollow>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsSplineFollowData, BovineLabs.Timeline.Physics.ActiveSplineFollow, BovineLabs.Timeline.Physics.PhysicsSplineFollowMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsSplineFollowState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsTeleportData, BovineLabs.Timeline.Physics.PhysicsTeleportAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsTeleportData, BovineLabs.Timeline.Physics.PhysicsTeleportAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsTeleportData, BovineLabs.Timeline.Physics.PhysicsTeleportAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsTeleportData, BovineLabs.Timeline.Physics.PhysicsTeleportAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentDrainableTrackJob<BovineLabs.Timeline.Physics.PhysicsTeleportData, BovineLabs.Timeline.Physics.ActiveTeleport, BovineLabs.Timeline.Physics.PhysicsTeleportState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.LatchDrainFinalizeJob<BovineLabs.Timeline.Physics.ActiveTeleport, BovineLabs.Timeline.Physics.PhysicsTeleportState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsTeleportData, BovineLabs.Timeline.Physics.ActiveTeleport, BovineLabs.Timeline.Physics.PhysicsTeleportMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsTeleportState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsVelocityClampData, BovineLabs.Timeline.Physics.PhysicsVelocityClampAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsVelocityClampData, BovineLabs.Timeline.Physics.PhysicsVelocityClampAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsVelocityClampData, BovineLabs.Timeline.Physics.PhysicsVelocityClampAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsVelocityClampData, BovineLabs.Timeline.Physics.PhysicsVelocityClampAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentTrackJob<BovineLabs.Timeline.Physics.PhysicsVelocityClampData, BovineLabs.Timeline.Physics.ActiveVelocityClamp>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsVelocityClampData, BovineLabs.Timeline.Physics.ActiveVelocityClamp, BovineLabs.Timeline.Physics.PhysicsVelocityClampMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsVelocityClampState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsLinearPIDData, BovineLabs.Timeline.Physics.PhysicsLinearPIDAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsLinearPIDData, BovineLabs.Timeline.Physics.PhysicsLinearPIDAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsLinearPIDData, BovineLabs.Timeline.Physics.PhysicsLinearPIDAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsLinearPIDData, BovineLabs.Timeline.Physics.PhysicsLinearPIDAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentDrainableTrackJob<BovineLabs.Timeline.Physics.PhysicsLinearPIDData, BovineLabs.Timeline.Physics.ActiveLinearPid, BovineLabs.Timeline.Physics.PhysicsLinearPIDState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.LatchDrainFinalizeJob<BovineLabs.Timeline.Physics.ActiveLinearPid, BovineLabs.Timeline.Physics.PhysicsLinearPIDState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsLinearPIDData, BovineLabs.Timeline.Physics.ActiveLinearPid, BovineLabs.Timeline.Physics.PhysicsLinearPIDMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsLinearPIDState>))]

[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsAngularPIDData, BovineLabs.Timeline.Physics.PhysicsAngularPIDAnimated>.ResizeJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsAngularPIDData, BovineLabs.Timeline.Physics.PhysicsAngularPIDAnimated>.AnimateUnblendedJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.TrackBlendImpl<BovineLabs.Timeline.Physics.PhysicsAngularPIDData, BovineLabs.Timeline.Physics.PhysicsAngularPIDAnimated>.AccumulateWeightedAnimationJob))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.PrepareAnimatedJob<BovineLabs.Timeline.Physics.PhysicsAngularPIDData, BovineLabs.Timeline.Physics.PhysicsAngularPIDAnimated>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.DisableAbsentDrainableTrackJob<BovineLabs.Timeline.Physics.PhysicsAngularPIDData, BovineLabs.Timeline.Physics.ActiveAngularPid, BovineLabs.Timeline.Physics.PhysicsAngularPIDState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.LatchDrainFinalizeJob<BovineLabs.Timeline.Physics.ActiveAngularPid, BovineLabs.Timeline.Physics.PhysicsAngularPIDState>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.WriteActiveJob<BovineLabs.Timeline.Physics.PhysicsAngularPIDData, BovineLabs.Timeline.Physics.ActiveAngularPid, BovineLabs.Timeline.Physics.PhysicsAngularPIDMixer>))]
[assembly: RegisterGenericJobType(typeof(BovineLabs.Timeline.Physics.Infrastructure.ResetStateAlwaysTrackJob<BovineLabs.Timeline.Physics.PhysicsAngularPIDState>))]
